### ISSUE TITLE
LaunchFile or what are the desired Nodes?

### ISSUE THREAD

**Issue by kurjam18** [lukovicaleksa/autonomous-driving-turtlebot-with-reinforcement-learning#4]
Hello,
I saw your great YouTube Video, and I wanted to try this by myself.  After I read your ReadMe.md I was a bit confused, because there where no explanation how to launch this project.  Can You just explain which of the nodes you used or share a launchflie  to start the project in the right way. 

I would be really happy to get an answer.

**Comment by lukovicaleksa** [comment]
After exporting the model and running the gazebo world map, you can run control_node.py and the robot will execute the path which can be selected on the top of the file.
