### ISSUE TITLE
Real world error

### ISSUE THREAD

**Issue by amelia413** [lukovicaleksa/autonomous-driving-turtlebot-with-reinforcement-learning#7]
Hey,
first of all, amazing work! secondly, in the simulation everything worked fine but in real world , it gives an error.
lidar_right = min(lidar[(ANGLE_MAX - HORIZON_WIDTH):(ANGLE_MAX)])
ValueError: min() arg is an empty sequence
I have set REAL_ROBOT = True

**Comment by lukovicaleksa** [comment]
Hi Amelia,

Thank you! I'm glad you find it useful.
This error looks to me like there is no Lidar data incoming.
Can you confirm that lidar data is ok?

Best regards,
Aleksa

**Comment by amelia413** [comment]
I tested the basic turtlebot3 object detection node and it worked fine with lidar.

**Comment by lukovicaleksa** [comment]
Okey but at some point the data was not available, I probably did not take
this into account when I was working on the project.
I suggest you write some code to handle this situation, but before that
just make sure that this really is the problem by for example printing the
lidar data.

**Comment by amelia413** [comment]
1.Which exact file do you run to generate a new Q table ?
    I created a new folder in 'DATA'. Do I have to create the individual files as well ?
    I received a ModelState not defined error.
2. LOG_DIR = DATA_PATH + '/Log_feedback' , should this be Log_feedback_1/2/3 ?
3. If I run rosrun master_rad control_node.py in turtlebot3_house.launch it gives me the following error

**Comment by amelia413** [comment]
Also I did print('\r\n', distance, '\r\n') to get Lidar reading. And I'm getting the readings, but still the error that 
    lidar_right = min(lidar[(ANGLE_MAX - HORIZON_WIDTH):(ANGLE_MAX)])
ValueError: min() arg is an empty sequence
[laser_distance_reading.txt](https://github.com/lukovicaleksa/autonomous-driving-turtlebot-with-reinforcement-learning/files/9959636/laser_distance_reading.txt)
